print("I am a genie. You have three wishes.")
firstWishVar = input("What is your first wish? ")
secondWishVar = input("What is your second wish? ")
thirdWishVar = input("What is your third wish? ")
print("Your wishes are "  + firstWishVar + ", " + secondWishVar + ", and " + thirdWishVar + ".")
